# Generated by Django 5.2.8 on 2025-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0002_usagelog_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
